---
:global:
    NServiceBus.CustomChecks.SqlServer:
      library_type: nservicebus-custom-check
    NServiceBus.CustomChecks.ElasticSearch:
      library_type: nservicebus-custom-check
    NServiceBus.CustomChecks.Http:
      library_type: nservicebus-custom-check

appveyor.yml:
  delete: true

Directory.Build.props:
  nservicebus-custom-check:
    nuget-package-tags:
      - nservicebus
      - customcheck
      - healthcheck
