name: Pull Request Checks

on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-version:
    # Environment
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      # Configure git user and email
      - name: "Configure git user and email"
        if: ${{ github.repository_owner == 'TraGicCode' }} # investigate this for security concerns and learning
        run: |
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.name "TraGicCode"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --global user.name "TraGicCode"

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      # - name: Run msync
      #   run: |
      #     gem install modulesync
      #     msync update --noop

      # - name: Run msync update
      #   if: ${{ github.repository_owner == 'TraGicCode' }}
      #   run: |
      #     gem install modulesync
      #     msync update --pr --amend --force
      - name: Run msync update
        if: ${{ github.repository_owner == 'TraGicCode' }}
        shell: pwsh
        run: |
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.name "TraGicCode"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --global user.name "TraGicCode"
          gem install modulesync
          msync update --noop
          & ./scripts/commit-and-push-file-changes.ps1
          msync update --pr --amend --git_base "https://${{ secrets.GITHUB_TOKEN }}@github.com/" --force 